export const FETCH_ALL_ALBUM = "FETCH_ALL_ALBUM";
export const GET_SINGLE_ALBUM = "GET_SINGLE_ALBUM";
export const CREATE_ALBUM_START = "CREATE_ALBUM_START";
export const UPDATE_ALBUM_START = "UPDATE_ALBUM_START";
export const DELETE_ALBUM_START = "DELETE_ALBUM_START";
