export const GET_SINGLE_TRACK = "GET_SINGLE_TRACK";
export const FETCH_ALL_TRACKS = "FETCH_ALL_TRACKS";
export const CREATE_SINGLE_TRACK = "CREATE_SINGLE_TRACK";
export const UPDATE_SINGLE_TRACK = "UPDATE_SINGLE_TRACK";
export const DELETE_SINGLE_TRACK = "DELETE_SINGLE_TRACK";
